spring:
  application:
    name: ts-station-service
  datasource:
    url: jdbc:mysql://${STATION_MYSQL_HOST:ts-station-mysql}:${STATION_MYSQL_PORT:3306}/${STATION_MYSQL_DATABASE:ts-station-mysql}?useSSL=false
    username: ${STATION_MYSQL_USER:root}
    password: ${STATION_MYSQL_PASSWORD:Abcd1234#}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

# HTTP Server
server:
  port: 8080  # HTTP (Tomcat) port

swagger:
  controllerPackage: fdse.microservice